Start time: 23:02
/home/mocheng/code/FANNBench/utils/pymilvus_ivfpq.py:203: SyntaxWarning: invalid escape sequence '\%'
  print("recall dist(10\% per bucket): ", hist)
Traceback (most recent call last):
  File "/home/mocheng/code/FANNBench/utils/pymilvus_ivfpq.py", line 3, in <module>
    from pymilvus import DataType, MilvusClient
ModuleNotFoundError: No module named 'pymilvus'
Start time: 23:03
error wrong argument size
Start time: 23:04
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/attr_sel_1_8_random.json
query range file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/qrangesel_1_8_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/sif_gt_10.json
K: 10
nprobe: 100
collection name: collection_sift1M_sel_1_8_random
get dataset size: 1000000  d: 128
dim: 128
_N: 1000000  N: 1000000
RPC error: [create_index], <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-11-20 15:04:09.023371', 'RPC error': '2024-11-20 15:04:09.027231'}>
Failed to create an index on collection: collection_sift1M_sel_1_8_random
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 119, in <module>
    client.create_collection(collection_name=c_name, 
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 91, in create_collection
    return self._create_collection_with_schema(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 631, in _create_collection_with_schema
    self.create_index(collection_name, index_params, timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 154, in create_index
    self._create_index(collection_name, index_param, timeout=timeout, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 176, in _create_index
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 165, in _create_index
    conn.create_index(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 148, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 144, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 183, in handler
    return func(self, *args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 986, in create_index
    check_status(status)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>
Start time: 23:10
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/attr_sel_1_8_random.json
query range file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/qrangesel_1_8_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/sif_gt_10.json
K: 10
nprobe: 100
collection name: collection_sift1M_sel_1_8_random
get dataset size: 1000000  d: 128
dim: 128
_N: 1000000  N: 1000000
RPC error: [create_index], <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-11-20 15:10:30.377436', 'RPC error': '2024-11-20 15:10:30.381690'}>
Failed to create an index on collection: collection_sift1M_sel_1_8_random
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 119, in <module>
    client.create_collection(collection_name=c_name, 
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 91, in create_collection
    return self._create_collection_with_schema(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 631, in _create_collection_with_schema
    self.create_index(collection_name, index_params, timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 154, in create_index
    self._create_index(collection_name, index_param, timeout=timeout, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 176, in _create_index
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 165, in _create_index
    conn.create_index(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 148, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 144, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 183, in handler
    return func(self, *args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 986, in create_index
    check_status(status)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>
Start time: 23:11
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/attr_sel_1_8_random.json
query range file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/qrangesel_1_8_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/sif_gt_10.json
K: 10
nprobe: 100
collection name: collection_sift1M_sel_1_8_random
get dataset size: 1000000  d: 128
dim: 128
_N: 1000000  N: 1000000
RPC error: [create_index], <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-11-20 15:11:12.817471', 'RPC error': '2024-11-20 15:11:12.821805'}>
Failed to create an index on collection: collection_sift1M_sel_1_8_random
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 119, in <module>
    client.create_collection(collection_name=c_name, 
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 91, in create_collection
    return self._create_collection_with_schema(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 631, in _create_collection_with_schema
    self.create_index(collection_name, index_params, timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 154, in create_index
    self._create_index(collection_name, index_param, timeout=timeout, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 176, in _create_index
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 165, in _create_index
    conn.create_index(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 148, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 144, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 183, in handler
    return func(self, *args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 986, in create_index
    check_status(status)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>
Start time: 23:11
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/attr_sel_1_8_random.json
query range file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/qrangesel_1_8_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/sif_gt_10.json
K: 10
nprobe: 100
collection name: collection_sift1M_sel_1_8_random
get dataset size: 1000000  d: 128
dim: 128
_N: 1000000  N: 1000000
RPC error: [create_index], <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-11-20 15:11:22.097927', 'RPC error': '2024-11-20 15:11:22.102162'}>
Failed to create an index on collection: collection_sift1M_sel_1_8_random
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 119, in <module>
    client.create_collection(collection_name=c_name, 
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 91, in create_collection
    return self._create_collection_with_schema(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 631, in _create_collection_with_schema
    self.create_index(collection_name, index_params, timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 154, in create_index
    self._create_index(collection_name, index_param, timeout=timeout, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 176, in _create_index
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 165, in _create_index
    conn.create_index(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 148, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 144, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 183, in handler
    return func(self, *args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 986, in create_index
    check_status(status)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>
Start time: 23:13
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/attr_sel_1_8_random.json
query range file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/qrangesel_1_8_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/sif_gt_10.json
K: 10
nprobe: 100
collection name: collection_sift1M_sel_1_8_random
collection  collection_sift1M_sel_1_8_random  exists
get dataset size: 1000000  d: 128
dim: 128
_N: 1000000  N: 1000000
RPC error: [create_index], <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-11-20 15:13:26.433238', 'RPC error': '2024-11-20 15:13:26.437960'}>
Failed to create an index on collection: collection_sift1M_sel_1_8_random
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 120, in <module>
    client.create_collection(collection_name=c_name, 
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 91, in create_collection
    return self._create_collection_with_schema(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 631, in _create_collection_with_schema
    self.create_index(collection_name, index_params, timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 154, in create_index
    self._create_index(collection_name, index_param, timeout=timeout, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 176, in _create_index
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 165, in _create_index
    conn.create_index(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 148, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 144, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 183, in handler
    return func(self, *args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 986, in create_index
    check_status(status)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>
Start time: 23:18
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/attr_sel_1_8_random.json
query range file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/qrangesel_1_8_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/sif_gt_10.json
K: 10
nprobe: 100
collection name: collection_sift1M_sel_1_8_random
collection  collection_sift1M_sel_1_8_random  exists, then drop it
get dataset size: 1000000  d: 128
dim: 128
_N: 1000000  N: 1000000
RPC error: [create_index], <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-11-20 15:18:44.551588', 'RPC error': '2024-11-20 15:18:44.556437'}>
Failed to create an index on collection: collection_sift1M_sel_1_8_random
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 120, in <module>
    client.create_collection(collection_name=c_name, 
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 91, in create_collection
    return self._create_collection_with_schema(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 631, in _create_collection_with_schema
    self.create_index(collection_name, index_params, timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 154, in create_index
    self._create_index(collection_name, index_param, timeout=timeout, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 176, in _create_index
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 165, in _create_index
    conn.create_index(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 148, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 144, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 183, in handler
    return func(self, *args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 986, in create_index
    check_status(status)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>
Start time: 23:53
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/attr_sel_1_8_random.json
query range file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/qrangesel_1_8_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/sif_gt_10.json
K: 10
nprobe: 100
collection name: collection_sift1M_sel_1_8_random
collection  collection_sift1M_sel_1_8_random  exists, then drop it
get dataset size: 1000000  d: 128
dim: 128
_N: 1000000  N: 1000000
partition M: 4
nlist: 1000
RPC error: [create_index], <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-11-20 15:54:00.035674', 'RPC error': '2024-11-20 15:54:00.039883'}>
Failed to create an index on collection: collection_sift1M_sel_1_8_random
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 124, in <module>
    client.create_collection(collection_name=c_name, 
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 91, in create_collection
    return self._create_collection_with_schema(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 631, in _create_collection_with_schema
    self.create_index(collection_name, index_params, timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 154, in create_index
    self._create_index(collection_name, index_param, timeout=timeout, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 176, in _create_index
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 165, in _create_index
    conn.create_index(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 148, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 144, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 183, in handler
    return func(self, *args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    raise e from e
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 986, in create_index
    check_status(status)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=parameter `m` not found: invalid parameter[expected=valid index params][actual=invalid index params])>
Start time: 23:54
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/attr_sel_1_8_random.json
query range file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/qrangesel_1_8_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/sel_1_8_random/sif_gt_10.json
K: 10
nprobe: 100
collection name: collection_sift1M_sel_1_8_random
collection  collection_sift1M_sel_1_8_random  exists, then drop it
get dataset size: 1000000  d: 128
dim: 128
_N: 1000000  N: 1000000
partition M: 4
nlist: 1000
start insertion
insert batch: 0.0
insert batch: 1.0
insert batch: 2.0
insert batch: 3.0
insert batch: 4.0
insert batch: 5.0
insert batch: 6.0
insert batch: 7.0
insert batch: 8.0
insert batch: 9.0
insert suc, time cost: 31.655191898345947
construction done
